### ISSUE TITLE
parse_frame returns unexpected result

### ISSUE THREAD

**Issue by Schwaneberg** [mtdcr/pysml#13]
The type hint `Tuple[int, Optional[SmlFrame]]` is ok for the first return `return [match.end(), obj]` (hoewever, `List[int, Optional[SmlFrame]]` would be the acurate hint), but not for the second `return [end]`.

This causes an unexpected ValueError, if you do stuff like `_, frame =  SmlBase.parse_frame(sml_frame)`.

**Comment by Schwaneberg** [comment]
I recommend to change the second return to `return (end, None)`

**Comment by mtdcr** [comment]
You're right. Would you mind creating a PR? Otherwise I'll fix it by myself, but it may take some more time.

I guess it would make sense to change the type annotation from Tuple to List and always return a list.

**Comment by mtdcr** [comment]
I failed trying to fix the signature of the existing function. Therefore, release 0.1.0 contains a new function called `find_frame` which always returns a fixed-size tuple. New code should prefer this function over the older `parse_frame`.

Thank you for your report! I'm sorry for the long delay.

**Comment by Schwaneberg** [comment]
Thank you very much! I could have created the PR - sorry I didn't respond
in time.

Am So., 8. Okt. 2023 um 12:36 Uhr schrieb mtdcr ***@***.***>:
