### ISSUE TITLE
SmlParserError: CRC16 mismatch

### ISSUE THREAD

**Issue by Panzer-bit** [mtdcr/pysml#2]
Hi,
I am using hass.io docker container on a synology nas. Is it possible to use edl21 add on in HA together with a usb-Weidmann adapter? 

Ssh “Cat /dev/ttyUSB0” is showing binary results, but there is no edl21 component at HA and no sensors listed. Config yaml is customized as needed.

Any ideas to get this working?

thanks a lot!

**Comment by mtdcr** [comment]
If the adapter delivers raw data, then it should work. Seeing binary data on ttyUSB0 is a good.

Your meter possibly doesn't get recognized by the edl21 component, yet. If that's the case, you should find related messages in Home Assistant's log. Can you take a look and report the log entries here?

**Comment by Panzer-bit** [comment]
Hi, i can see Wh in sensor at HA now. But don’t ask me why.
My log is full of Errors likes:
2021-01-26 22:15:13 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback SerialTransport._read_ready()
Traceback (most recent call last):
File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.8/site-packages/serial_asyncio/__init__.py", line 119, in _read_ready
self._protocol.data_received(data)
File "/usr/local/lib/python3.8/site-packages/sml/asyncio.py", line 61, in data_received
res = self.parse_frame(self._buf)
File "/usr/local/lib/python3.8/site-packages/sml/__init__.py", line 415, in parse_frame
obj = SmlFrame(SmlBase.__unescape(frame[8:-8-padding]))
File "/usr/local/lib/python3.8/site-packages/sml/__init__.py", line 377, in __init__
self.append(SmlMessage(self.bits))
File "/usr/local/lib/python3.8/site-packages/sml/__init__.py", line 316, in __init__
raise SmlParserError('CRC16 mismatch')
sml.SmlParserError: CRC16 mismatch

Could you please help?

**Comment by mtdcr** [comment]
Can you capture a minute of ttyUSB0 traffic to a file and send it to me by mail (obi at saftware dot de)?

Just do `cat /dev/ttyUSB0 > dump.bin` when Home Assistant is not running, and abort with Ctrl-C after a while.

**Comment by dannerph** [comment]
Hi there, I think I might have the same issue on a newly installed Iskra MT691: CRC16 missmatch.

**Comment by Panzer-bit** [comment]
Sorry for my late reply. I tried now several things, but i don’t get it working. When I ssh  cat /dev/ttyUSB0, it returns to command prompt for new commands in a second on my Synology. On my raspi there it drops all infos needed inkl. ISRKA..etc.
I think the issue is my Synology mapping. Dmesg is showing everything is correct. Thanks again and hopefully you have one more idea

**Comment by dannerph** [comment]
@Panzer-bit so you are also trying to get data from a ISKRA metering device?
I captured the readings, but it seems for me that the SML is corrupt with this device. I mainly receive SML starting but no ending including CRC.

However, I need to test it again with info mode on.

**Comment by Panzer-bit** [comment]
@dannerph yes, and now i get data. The following Start/Skript helped me on my Synology to finally get data now.

https://community.openhab.org/t/get-serial-devices-working-on-synology-ds216-ii-diskstation/36072

 But I don’t get update-data. When I am restarting HASS, it gets the update. Any ideas on this?

Why do you think there is no ending CRC?

Thanks again

**Comment by dannerph** [comment]
I am using hass.io on a raspberry pi 4, serial is working fine. However, I inspected the captured bitstream and found out that the SML data seems to be not as defined in the SML specification. Thus cannot be interpreted correctly by this python library.

**Comment by mtdcr** [comment]
@dannerph Thank you, that's very helpful information. Can you take a look at two commits from forked repositories? They seem to handle a similar problem.

- https://github.com/lsprophe/pysml-1/commit/de6176c2c19146582bf5f4fa92f4847b1c3e5fd0
Note that this patch modifies the return type of `SmlBase.parse_frame()`, so `SmlProtocol.data_received()` will need adjustment.

- https://github.com/troffmo5/pysml/commit/420d464c506cc9cb03f014270b981fdaba0d1621
If this patch solves the problem, I'd prefer it for its simplicity.

Regarding your change to the EDL21 component, would you like to make min_time configurable?

**Comment by mtdcr** [comment]
https://github.com/mtdcr/pysml/commit/79894a87b21776e81b4ad6971a8773dbcf5619b1 might fix the CRC issue (c.f. #3).

**Comment by dannerph** [comment]
@mtdcr: I will check it on Sunday and report back.
Catching the SmlParserError in the asyncio protocol to reset the buffer would make sense to me in any case.

Correct, currently I copied the component as custom component and removed the limiting part, so that I get all incoming measurements. configurable (optional) min_time would be perfect.
If you need some help, I could prepare a PR for that? Easiest way would be to combine this small change with a library update to avoid overhead in the revieweing process at home assistant repo.

**Comment by mtdcr** [comment]
I'd welcome a PR, as I'm currently not actively using the edl21 integration (moved over to [sml-mqtt-bridge.py](https://github.com/mtdcr/pysml/blob/master/examples/sml-mqtt-bridge.py)).

**Comment by dannerph** [comment]
@mtdcr mhm fix_crc16 branch does not work for me. On fix_crc16 branch no message is received correctly. The code from @kheinz57 (PR) however is working.

**Comment by mtdcr** [comment]
@dannerph: Just found and fixed a major bug in 0.0.4. Can you try 0.0.5, please?

**Comment by dannerph** [comment]
@mtdcr thanks for your effort! v0.0.5 seems to work fine via my laptop! I tested it for several minutes without any issues. I will now hack it into my hass.io installation and will report back tomorrow for "long-term" experience.

**Comment by dannerph** [comment]
if @Panzer-bit has nothing against, we could close this issue.

**Comment by kheinz57** [comment]
Nice to see it fixed!
