### ISSUE TITLE
Connection loss not detected

### ISSUE THREAD

**Issue by Lemocin** [mtdcr/pysml#7]
I use the edl21 platform on Home Assistant. My reader is connected via a wemos d1 with espeasy and this entry: 
```
platform: edl21
serial_port: socket://192.168.178.212:23
```
If my esp loses connection to the router, the router restarts, or something loses power no new data is received. I did a automation which restarts the whole Home Assistant, if no new data is being received for 5 minutes but that is not an optimal solution.

I also did a fix in my local installation, which works for me and a friend of mine, who has the same issue, but, as it is local, is not update-safe.

**Comment by mtdcr** [comment]
I think it would benefit more people and projects if this was handled at a lower layer. `pyserial` should know when a disconnection event happened and either it or `pyserial-asyncio` should be able to propagate this event or try to reconnect. It's comparable to a serial cable being unplugged for some time, so trying to reconnect under the hood seems sensible to me.

**Comment by Lemocin** [comment]
I totally agree, but it seems that there is no such method to detect a connection loss yet. The only timeout which the Event Loop connections are implementing are from the connection building. If the connection is lost, there is no working method to detect it from what i have seen. 
I tried some methods from the transports like `is_closing()` but this only detects a properly closed connection and not a lost one.

**Comment by mtdcr** [comment]
Fixed by PR #8
